### PR TITLE
Fixed 60-sensor.hwdb hyperlink and corrected GeoClue spelling.

### PR DESCRIPTION
**Pull request by nodeg**

### CODE REVIEW

**Comment by hadess** [comment]
Could you please split those up and follow the other commits to that same file for an example on how to format it?

**Comment by nodeg** [comment]
Can you specify the "format" part a little bit, please? I looked at the previous commits to README.md and I am not sure what "format" I should use. Thanks.

**Comment by hadess** [comment]
> Can you specify the "format" part a little bit, please? I looked at the previous commits to README.md and I am not sure what "format" I should use. Thanks.

The commit message needs to reflect the individual changes, not be everything lumped together.

```
README: Fix link to systemd ACCEL_MOUNT_MATRIX documentation
```
and:
```
README: Fix GeoClue spelling
```

**Comment by hadess** [comment]
I pushed those manually.

**Pull request closed without merging**
