### PR TITLE
main: Add IIO buffering compass support

### PR DESCRIPTION
**Pull request by elad661**
This (kinda) works on the thinkpad twist, with the only issue is the values returned from the compass are not even remotely accurate :)

The numbers returned from the compass are always larger than 360 (at least on my device), and they never show the correct heading. 

(I initially thought calculating it manually from the magn_x and magn_y channels would work better for me, but it turns out they're less accurate and I was reading the numbers wrong)

I also tried using the scale value the sensor has, but that's even worse - the scale is 0.000001, which is very unhelpful... I think it is very likely that the hardware I have is just plainly bad, and that the code itself works as intended.

### CODE REVIEW

**Comment by hadess** [comment]
Can you contact the linux-iio mailing-list to talk about the units and values reported by the driver? I couldn't find anything useful in Documentation/ABI/testing/sysfs-bus-iio

**Comment by elad661** [comment]
Sorry for the long delay.

I've split up the commits as requested and fixed up the indentations errors.

I also figured out that to get the actual value in degrees out of the compass all I had to do is to divide it by 10, and changed heading to int because I don't think fractions of degrees would be useful for anyone.

**Comment by hadess** [comment]
I would actually prefer to keep heading as a float. Heading is a gdouble in geoclue:
http://cgit.freedesktop.org/geoclue/commit/?id=6808be68f3f3f07bd98a47099d66d49f85dfbf37

About the "divide by 10", that value should be in one of the sysfs files, see the "Find the scale" section in iio-buffer-utils.c

**Comment by elad661** [comment]
It would make sense the scale would be in the sysfs files, but it's not... in_magn_scale and in_rot_scale both return 0.000001

if it helps I can ask why it's like this on the iio mailing list.

**Comment by hadess** [comment]
That would be helpful, yes.

**Comment by hadess** [comment]
Note that you'll also need to:
1) add a .set_polling driver method
2) add support for compasses in monitor-sensor.c

**Comment by hadess** [comment]
Merged with plenty of fixes from Zeeshan and myself. Will follow up on the couple of TODO items in other issues.

**Comment by zeenix** [comment]
:+1: 

Thanks. Me and Matthias tested on the only hardware we had at hackfest and seems the value we were getting was out of scale (16xxxx something). Looking at the code, it seems we still need that to be fixed in the kernel? It's been a long time since I did any kernel programming but I could give it a go if I had the hardware. :(

Oh and it seems you want geoclue to transform the magnetic to true heading. :) You found some formula somewhere to do that, right?

**Comment by elad661** [comment]
@zeenix I found a Python implementation: https://github.com/cmweiss/geomag/blob/master/geomag/geomag/geomag.py

It seems to use the magnetic model from NOAA: http://www.ngdc.noaa.gov/geomag/WMM/

**Comment by elad661** [comment]
@zeenix I also found a C implementation (which seems to be under public domain): http://www.ngdc.noaa.gov/geomag/WMM/soft.shtml

**Comment by zeenix** [comment]
@elad661 :+1: Interesting! I'll look into them. The python code went quite above my head though. :)

**Pull request closed without merging**
