### PR TITLE
Confirmed working on Huawei Matebook X Pro

### PR DESCRIPTION
**Pull request by aymanbagabas**
Tested on Archlinux-ck kernel 4.17.8-1-ck

### CODE REVIEW

**Comment by rien333** [comment]
How do I know wether this program is working?

Running `monitor-sensor` outputs:
```
Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
**
ERROR:monitor-sensor.c:165:appeared_cb: assertion failed (error == NULL): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.7460 was not provided by any .service files (g-dbus-error-quark, 2)
fish: “monitor-sensor” terminated by signal SIGABRT (Abort)
```

**Comment by hadess** [comment]
> How do I know wether this program is working (on my matebook, with arch linux)?

iio-sensor-proxy crashed, try the latest version and file a bug if it still happens.

**Comment by hadess** [comment]
@aymanbagabas please follow the commit message style for the updates to README.md. Looks fine otherwise.

**Comment by rien333** [comment]
I've opened an issue (#237 ) because it doesn't seem to be working for me (I have the i7 model). @aymanbagabas if you have any info to share at what I'm potentially missing please let me know in the issue.

**Comment by aymanbagabas** [comment]
> @aymanbagabas please follow the commit message style for the updates to README.md. Looks fine otherwise.

What am I missing?

**Comment by hadess** [comment]
> @aymanbagabas please follow the commit message style for the updates to README.md. Looks fine otherwise.

Those are the past changes made to README.md:
https://github.com/hadess/iio-sensor-proxy/commits/master/README.md

**Comment by aymanbagabas** [comment]
> > @aymanbagabas please follow the commit message style for the updates to README.md. Looks fine otherwise.
> 
> Those are the past changes made to README.md:
> https://github.com/hadess/iio-sensor-proxy/commits/master/README.md

Done

**Pull request merged**
