### PR TITLE
Add lenovo yoga 2 13" to the tested devices list.

### PR DESCRIPTION
**Pull request by vinilox**

### CODE REVIEW

**Comment by vinilox** [comment]
Done.

**Comment by hadess** [comment]
You need to squash all the commits and force the push. I can't push 3 commits to add one line, especially when some of the commits have conflict marks in them.

**Comment by vinilox** [comment]
Yes, I am working on it sorry.

**Comment by vinilox** [comment]
It should be ok. Sorry for the trouble.

**Pull request merged**
