### PR TITLE
drv-iio-compass: Change the compass channel name

### PR DESCRIPTION
**Pull request by soda0289**
The channel name should not include _raw as the name will not include this. This fixes an issue where the compass would not return any data on a Surface Pro 2.

### CODE REVIEW

**Comment by hadess** [comment]
I don't see why it wouldn't be available, it's the same value, without the scale and offsets already applied. You should send a mail to the linux-iio mailing-list and check that you're running the latest kernel.

**Comment by soda0289** [comment]
The _raw is not needed in the process_scan_1 function. This function looks up the channel by it's channel name or in this case "in_rot_from_north_magnetic_tilt_comp". The channel name does not include _raw as it is read from the file ending in _en from the scanning_element folder, in build_channel_array function. 

The other drivers, light and accel, also do not include _raw as I think it is stored in the full device path stored in or_data->dev_path.

**Comment by hadess** [comment]
Can you update the commit message to mention that? Because it's not clear from the original request.

**Comment by hadess** [comment]
And also remove the error reporting, or make it a separate commit.

**Comment by soda0289** [comment]
I will update the commit message and make two commits. Maybe add the present_level check for the other iio drivers.

Thanks

**Comment by hadess** [comment]
> Maybe I can add the present_level check for the other iio drivers.

Would be best to move this error message in process_scan_1 instead then.

**Comment by soda0289** [comment]
Moved warning into scan_1

**Pull request closed without merging**
